<?php

namespace BvCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository {
    
   
    public function getCmsGridList($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper, $user) {

        $data = $this->trim_serach_data($searchData, $SearchType);

        
        $query = $this->createQueryBuilder('c')
		//		        ->where('c.status != :status')
		//		        ->setParameter('status', 'Deleted')
                ;
        
        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }
        
        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $countCms = count($query->getQuery()->getArrayResult());
        $query->orderBy($order_by, $sort_order);
        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        $result = $query->getQuery()->getArrayResult();

        $dataResult = array();

        if (count($result) > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countCms;

            return $dataResult;

        }
        return false;
    }

    public function trim_serach_data($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {
                    
                    if ($key == 'Name' && !empty($val)) {
                        
                        $QueryStr[$i]['Field'] = 'c.name';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'Meta Title' && !empty($val)) {
                        
                        $QueryStr[$i]['Field'] = 'c.metatitle';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'Meta Description' && !empty($val)) {
                    
                    	$QueryStr[$i]['Field'] = 'c.metadescription';
                    	$QueryStr[$i]['Value'] = $val;
                    	$QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    $i++;
                }
            } else {
                !empty($searchData['Name']) ? $QueryStr['c.name'] = $searchData['Name'] : "";
                !empty($searchData['Meta Title']) ? $QueryStr['c.metatitle'] = $searchData['Meta Title'] : "";
            }
        }
        return $QueryStr;
    }
}
